"""Initial database setup

Revision ID: b4987ab6f25f
Revises: fe43450be618
Create Date: 2025-10-20 15:48:49.649058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4987ab6f25f'
down_revision = 'fe43450be618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_restaurant_uc', ['food_user_id', 'restaurant_id'])

    with op.batch_alter_table('menu_dishes', schema=None) as batch_op:
        batch_op.create_unique_constraint('_dish_menu_uc', ['dish_id', 'menu_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_dishes', schema=None) as batch_op:
        batch_op.drop_constraint('_dish_menu_uc', type_='unique')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('_user_restaurant_uc', type_='unique')

    # ### end Alembic commands ###
